version: '3.8'

services:
  api:
    build:
      context: ./AI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "exit(0)"]
      interval: 30s
      timeout: 3s
      retries: 1
      start_period: 5s
